#####################################################
#   ╔═╗╔╦╗╔═╗ ╦╦ ╔═╗                              #
#   ║╣ ║║║║ ║ ║║ ╚═╗                              #
#   ╚═╝╩ ╩╚═╝╚╝╩ ╚═╝                              #
#####################################################

# Configuration file for emojis

#------------------------------------------------------------------------------
# General Emojis
#------------------------------------------------------------------------------

AMPBOT = "<:ampbot:1300481984295993344>"  # AMPBOT emoji